Update nss so that dependencies can be retrieved
Otherwise get "Could not transfer artifact ...
java.security.ProviderException: java.security.KeyException" errors